### ISSUE TITLE
Read default config from .sequelizerc

### ISSUE THREAD

**Issue by kristijan-blackshield** [doralteres/sequelize-mig-generator#15]
Hey @doralteres ,

first, I want to let you know that this tool is great, and I picked it up to handle migrations on my project. I hope this repo will be maintained since there is no good alternative to handle migrations, especially for cases like mine where I needed to generate all models based on the existing DB. The lack of model diff migration generation in Sequelize is really painful. Your tool works out of the box and that feature is also supported.

One thing for now to mention is not an issue since we have -m and -s flags to handle it. But for sequelize-mig-generator tool to read default folders for models and migrations from .sequelizerc.

Also, I'm interested in some future improvements, so if you have some goals that you would like to implement/accomplish please let me know.

**Comment by doralteres** [comment]
Hey @kristijan-blackshield thanks for the feedback!
- Using `.sequelizerc` file option is a great idea - I'll add it on the next release 😄 
- The main futuristic feature I want to add supports for sequelize v7 and more migration types like renaming tables, columns, etc.

**Comment by kristijan-blackshield** [comment]
I'm glad to hear that. One question, does this tool take into account indexes defined directly to the models? To explain what i mean this is an example model 
```
const { DataTypes } = require('sequelize');
module.exports = (sequelize) => {
    const attributes = {
        id: {
            type: DataTypes.INTEGER,
            allowNull: false,
            primaryKey: true,
            autoIncrement: true,
            field: 'id',
        },
        globalOperationId: {
            type: DataTypes.INTEGER,
            allowNull: true,
            defaultValue: null,
            primaryKey: false,
            autoIncrement: false,
            field: 'globalOperationId',
            references: {
                key: 'id',
                model: 'global_operations',
            },
        },
    };
    const options = {
        tableName: 'admin_permissions',

        indexes: [
            {
                name: 'globalOperationId',
                unique: false,
                type: 'BTREE',
                fields: ['globalOperationId'],
            },
        ],
    };
    const AdminPermissionsModel = sequelize.define('admin_permissions', attributes, options);
    return AdminPermissionsModel;
};
```
This index to globalOperationId?

**Comment by doralteres** [comment]
Hey @kristijan-blackshield 
just pushed the `.sequelizerc` file feat,  so it will be available soon on the next release 🥳 

about the indexes: I didn't check how they behave and set in the sequelize config and migrations. I suggest you to test it with the tool and if you will find some things go wrong or not supported yet - please open a separate issue 😄
